// Code generated by ent, DO NOT EDIT.

package ent

// CreateIdentityInput represents a mutation input for creating identities.
type CreateIdentityInput struct {
	Name string
}

// Mutate applies the CreateIdentityInput on the IdentityMutation builder.
func (i *CreateIdentityInput) Mutate(m *IdentityMutation) {
	m.SetName(i.Name)
}

// SetInput applies the change-set in the CreateIdentityInput on the IdentityCreate builder.
func (c *IdentityCreate) SetInput(i CreateIdentityInput) *IdentityCreate {
	i.Mutate(c.Mutation())
	return c
}
